source.jdbc.url=jdbc:yugabytedb://localhost:5434/testdb
source.jdbc.user=yugabyte
source.jdbc.password=yugabyte

target.jdbc.url=jdbc:yugabytedb://localhost:5434/testdb
target.jdbc.user=yugabyte
target.jdbc.password=yugabyte

target.schema=moneymovement_source
target.table=tbl_entityres_card_merchants

sql.start_date=2026-01-01
sql.end_date=2026-01-05

batch.enabled=false

copy.replace=true
copy.flush_every=1000

csv.delimiter=,
csv.null=\\N
csv.quote="
csv.escape="

jdbc.fetch_size=1000
spark.repartition=2

# jdbc.partition.column=transaction_posted_dt
# jdbc.partition.lower=2026-01-01
# jdbc.partition.upper=2026-01-05
# jdbc.partition.num=2

yb.disable_transactional_writes=true
